mod analysis;
pub(in crate::core::bundle) mod analyze;
mod classify;
pub(in crate::core::bundle) mod create_bundle;
pub(in crate::core::bundle) mod manifest;
mod materialize;
mod normalized;
pub(in crate::core::bundle) mod plan;
mod prepare;
mod projection;
mod source;
mod source_entry;
pub(in crate::core::bundle) mod tasks;
pub(in crate::core::bundle) mod types;
